name: ECR Push Image with Commit Message

on:
  push:
    branches:
      - 'main'
#    tags:
#      - v*  # 'v' で始まるタグに反応（例: v1.0.0）

jobs:
  extract-commit-message:
    runs-on: ubuntu-latest
    outputs:
      repository-name: ${{ steps.extract-repo-name.outputs.repository-name }}
    steps:
      - uses: actions/checkout@v3
      - id: extract-repo-name
        run: |
          repository_name=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          echo "::set-output name=repository-name::${repository_name}"

  push:
    if: ${{ needs.extract-commit-message.outputs.repository-name != ''}}
    runs-on: ubuntu-latest
    needs: extract-commit-message
    outputs:
      repository-name: ${{ steps.build-push.outputs.repository-name }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions

      # ECR ログイン
      - uses: aws-actions/amazon-ecr-login@v1

      # Docker イメージを build・push する
      - name: Build and push Docker image
        id: build-push
        run: |
          REPOSITORY_NAME=${{ needs.extract-commit-message.outputs.repository-name }}
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${REPOSITORY_NAME}:${{ github.sha }}"
          docker build -t ${IMAGE_URI} . -f ./docker/Dockerfile
          docker push ${IMAGE_URI}
          
          echo "::set-output name=repository-name::${REPOSITORY_NAME}"

  deploy:
    if: ${{ needs.push.outputs.repository-name != ''}}
    runs-on: ubuntu-latest
    needs: push
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions

      - name: Deploy to CloudFormation
        run: |
          REPOSITORY_NAME=${{ needs.push.outputs.repository-name }}
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${REPOSITORY_NAME}:${{ github.sha }}"
          aws cloudformation deploy \
            --template-file cloudformation/cloudformation-template.yaml \
            --stack-name ${REPOSITORY_NAME} \
            --parameter-overrides ImageUri=${IMAGE_URI} FunctionName=${REPOSITORY_NAME} \
            --capabilities CAPABILITY_IAM